sudo: required
dist: trusty
language: python

notifications:
  email: on_failure

# coverity stuff
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
    - secure: "JpBZGZhAtJtqL8mRo4nZ7btAH+kYrLvuBZvc08FQg5IBKZFGfMfl4weeZa2Z1v/eFI1ByDuotFeBGeKA93YSaRffXyWd1pr0uhdjsU8rR/8mD9OJDAytfai8N9gVmNMlnoRg4Fwy7PVy7qB47UhdIuymZXDpcFJd0bPeYjKc5vaLXlCHrsw+px/RZpHniBl4kd8WH586To4HN4SSwTESI2/S/8W19wOAGbmlUrzmFvjdFBs8Z77CpCf3wnwcMORPFuhx06FcPtAoxAmQvo7V/3G8/Ioh8sLnmVF1/CP7Qc/2s3aIe8cLTwGSQbtVtMAZrka0gkRK6dtELMBy9bQGmY9dXhZruT50q6bT4bgk+gouPgZvMHitqWx+0T5gH+Py1VxUfV7e2B+jJA4CrlTvhADaUIJN26vRplcZnghUma1O+2SedG4aJ3zilUZqOm3K9OpfCUM4mzn1FCAcmAslO3ZqqVteK6D612WPWO7Zt6ek4hCyABtrG6YreZ2xSAVYwhma/o4aqVBrGEfecpqMGb3aAZrXeLhA+7hq4leGKvpd3OYlpjhg1KRoM26G9dr6Ac/0EIPAnJ0tf2RGey+3U9D78B9yz3ymqBZLCpjyJ1BH2RjYpHxmU0A1Ud9gxKlIJaVJ5YK9UgOg2DQZDQz4rRhpfoTVIbtTSW2+NLLr1rk="

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libboost-dev
      - libeigen3-dev

  coverity_scan:
    project:
      name: "lwtnn/lwtnn"
      description: "lightweight neural network for C++"
    notification_email: dguest@cern.ch
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan

# python dependencies
python:
  - "3.4"
install:
  - pip install h5py
  - pip install pyyaml

# TODO: add some regression tests
script:
  - make
  - ./tests/test-agilepack.sh
  - ./tests/test-highway.sh
  - ./tests/test-ipmp.sh
  - ./tests/test-DL1.sh
